;ARITMETICA BASICA
 
org 100h  

;INCREMENTAR EL VALOR DE UN REGISTRO

mov AX,69H   ;ASIGNO 69H EN AX

inc AX       ;SUMO 1 EN AX

;DECREMENTAR EL VALOR DE UN REGISTRO

dec AX

;SUMA CORTA

mov AX,55H   ;ASIGNO 55H EN AX

mov BX,10H   ;ASIGNO 10H EN BX

add AX,BX    ;AX+BX -> LO GUARDO EN AX  

;RESTA CORTA

mov AX,55H   ;ASIGNO 55H EN AX

mov BX,10H   ;ASIGNO 10H EN BX

sub AX,BX    ;AX-BX -> LO GUARDO EN AX=(55H-10H)

;QUE PASA SI DA NEGATIVO? OSEA AX < BX

mov AX,10H   ;ASIGNO 10H EN AX

mov BX,55H   ;ASIGNO 55H EN BX

sub AX,BX    ;AX-BX -> LO GUARDO EN AX=(10H-55H) 
  
neg AX       ;CA2 EN AX OBTENGO EL NUMERO POSITIVO

;MULTIPLICACION CORTA

mov AL,10H   ;ASIGNO 10H A AL

mov BL,05H   ;ASIGNO 05H A BL

mul BL       ;AL*BL  -> LO GUARDO EN AX

;DIVISION CORTA

mov AX,100H   ;ASIGNO 100H A AX

mov DX,0H     ;INICIALIZO DX

mov CX,05H    ;ASIGNO 05H EN CX

div CX        ;AX/CX -> LO GUARDO EN AX y EL RESTO EN DX

ret






