;LEER CARACTERES

ORG 100H    ;CS:IP

;BLOQUE VIDEO
MOV AH,0H
MOV AL,0H
INT 10H              ;INTERRUPCION DE VIDEO

;BLOQUE MOSTRAR MSJE
MOV DX,OFFSET msje
MOV AH,9H
INT 21H              ;INTERRUPCION S.O

;BLOQUE MOSTRAR UN UNICO CARACTER "SALTO DE LINEA"

MOV AH,0EH           ;CONFIGURO PARA UN CARACTER

MOV AL,10H           ;SALTO DE LINEA

INT 10H              ;INTERRUPCION VIDEO


;BLOQUE MOSTRAR UN UNICO CARACTER "RETORNO DE CARRO"

MOV AH,0EH

MOV AL,13H           ;RETORNO DE CARRO

INT 10H


;BLOQUE SOLICITAR CARACTER

MOV AH,1    ;CONFIGURO PARA LEER 1 CARACTER

INT 21H     ;INTERRUPCION S.O 

;SE GUARDO EL VALOR EN AL COMO ASCCI

MOV BL,AL   ;GUARDO EL DATO EN BL

RET

msje db "dame un numero: $" 