;INICIALIZAR CS,DS,SS,ES

ORG 0100H       ;DIRECCION DE INICIO DONDE DEBE SER CARGADO EL PROGRAMA

.MODEL SMALL    ;ATRIBUTOS DE MEMORIA

.STACK 0100H    ;SS(SEGMENTO DE PILA)

.DATA           ;<- DS(SEGMENTO DE DATOS)

    MSG DB 'HOLA MUNDO$'
    
.CODE           ;<- CS(SEGMENTO DE CODIGO)

    MOV AX,@DATA
    
    MOV DS,AX   ;ASIGNO LA PRIMERA DIRECCION DEL SEGMENTO DE DATOS EN EL REGISTRO DE SEGMENTO DE DATOS

    MOV ES,AX   ;<- ES(SEGMENTO ESTRA DE DATOS) ASIGNA EL SEGMENTO DE DATOS EXTRA PUEDE SER OTRO SEGMENTO DE DATOS
   
    MOV SP,100H ;<- APUNTO AL SEGMENTO DE PILA 

    

.EXIT           ;FIN


