;MANIPULACION DE REGISTROS DE CONTROL

;DESHABILITAR-HABILITAR INTERRUPCIONES

CLI ;DESHABILITAR INTERRUPCIONES

STI ;HABILITAR INTERRUPCIONES

;LEER EL ESTADO DE UN BIT EN EL REGISTRO DE ESTADOS

PUSHF   ;GUARDAR EL VALOR ACTUAL DEL REGISTRO DE FLAG EN LA PILA

POP AX  ;CARGA EL VALOR DEL REGISTRO DE FLAG EN AX

AND AX,0001B ;REALIZA UNA OPERACION AND CON 0001B PARA AISLAR EL BIT DE CARRY

;EL BIT DE CARRY ESTARA AHORA EN EL BIT 0 DEL REGISTRO AX

;RESTAURAR EL VALOR ORIGINAL DEL REGISTRO DE FLAGS

POPF                                              

;COMO ESTABLECER EL BIT DE CARRY EN 1

STC ;Set Carry Flag ESTABLECE EL BIT DE CARRY (CF) EN 1

;TAMBIEN SE PUEDE...

PUSHF           ;GUARDA EL VALOR ORIGINAL EN EL REGISTRO DE FLAG EN LA PILA

POP AX          ;CARGAR EL VALOR DEL REGISTRO DE FLAG EN AX

OR AX,0001H     ;REALIZA UNA OPERACION OR CON 0001B PARA ESTABLECER EL BIT DE CARRY EN 1

PUSH AX         ;GUARDAR EL NUEVO VALOR DEL REGISTRO DE FLAG EN LA PILA

POPF            ;RESTAURA EL VALOR DEL REGISTRO DE FLAG


;CAMBIAR "MODOS DE PROCESADOR"

;EJEMPLO DE CAMBIO AL MODO VIRTUAL 8086

MOV AX,CS   ;CARGAR EL SELECTOR DE SEGMENTO DE CODIGO ACTUAL EN AX

OR AX,3h    ;ESTABLECER LOS BITS RPL (Requestor Privilege Level) EN 3

MOV CS,AX   ;ACTUALIZAR EL SELECTO DE SEGMENTO DE CODIGO CON EL NUEVO VALOR

;El modo virtual 8086 es un subconjunto del modo real que permite ejecutar múltiples tareas de 
;manera virtualizada. En el 8086, esto se logra mediante el cambio de segmentos y el uso de 
;instrucciones específicas como ENTER, LEAVE, IRET, entre otras.

;EJEMPLO USO DE SEGMENTACION

MOV AX,@DATA  ;EJEMPLO DE CAMBIAR EL SEGMENTO DE DATOS (DS)

MOV DS,AX 

;El 8086 utiliza segmentación para direccionar memoria. Puedes cambiar entre diferentes 
;segmentos utilizando registros de segmento como CS, DS, ES, SS.