;ESTRUCTURAS DE DATOS MATRIZ

ORG 0100H

.MODEL SMALL

.DATA

    matriz DW 3 DUP(3 DUP(?)) ;DEFINIR UNA MATRIZ 3X3 ELEMENTOS DE PALABRAS DE (16 BITS)
    
,CODE

    MOV AX,@DATA
    
    MOV DS,AX
    
    ;INICIALIZAR LA MATRIZ CON ALGUNOS VALORES
    
    MOV SI,OFFSET matriz        ;CARGAR LA DIRECCION BASE DE LA MATRIZ EN SI
    
    MOV CX,0003H            ;NUMERO DE FILAS DE LA MATRIZ
    
    FILA_LOOP:
    
        MOV DI,SI       ;CARGAR LA DIRECCION BASE DE LA FILA ACTUAL EN DI
        
        MOV BX,1        ;VALOR INICIAL A ASIGNAR A LA FILA
        
        MOV DX,3        ;NUMERO DE COLUMNAS DE LA MATRIZ
        
        COLUMNA_LOOP:
        
            MOV [DI],BX     ;ASIGNAR EL VALOR ACTUAL A LA POSICION DE LA MATRIZ
            
            ADD BX,0001H    ;INCREMENTAR EL VALOR PARA EL SIGUIENTE ELEMENETO
            
            ADD DI,2        ;AVANZAR AL SIGUIENTE ELEMENTO DE LA FILA
            
            LOOP COLUMNA_LOOP   ;REDUCIER EL PROCESO PARA TODAS LAS COLUMNAS
         
        ADD SI,6        ;AVANZAR A LA SIGUIENTE FILA
        
        LOOP FILA_LOOP  ;REPETIR EL PROCESO PARA TODAS LAS FILAS
        
    ;ACCEDER A UN ELEMENTO ESPECIFICO DE LA MATRIZ(POR EJEMPLO, EL ELEMENTO EN LA FILA 2, COLUMNA 1)
    
    MOV SI,OFFSET matriz    ;CARGAR LA DIRECCION BASE DE LA MATRIZ EN SI
    
    ADD SI,4                ;AVANZAR A LA SEGUNDA FILA(CADA FILA TIENE 2 BYTE * 3 COLUMNAS = 6 BYTES)
    
    ADD SI,2                ;AVANZAR A LA SEGUNDA COLUMNA (CADA COLUMNA TIENE 2 BYTES)
    
    MOV AX,[SI]             ;CARGAR EL VALOR DEL ELEMENTO EN AX
    
    ;MODIFICAR UN VALOR ESPECIFICO DE LA MATRIZ (POR EJEMEPLO EL ELEMENTO EN LA FILA 2, COLUMNA 1)
    
    MOV SI,OFFSET matriz    ;CARGAR LA DIRECCION BASE DE LA MATRIZ EN SI
    
    ADD SI,4                ;AVANZAR A LA SEGUNDA FILA(CADA FILA TOENE 2 BYTES  * 3 COLUMNAS = 6 BYTES) 
    
    ADD SI,2                ;AVANZAR A LA SEGUNDA COLUMNA (CADA COLUMNA TIENE 2 BYTES)
    
    MOV AX,100              ;NUEVO VALOR ASIGNAR AL ELEMENTO
    
    MOV [SI],AX             ;ASIGNAR EL NUEVO VALOR AL ELEMENTO
    
    ;EL CODIGO CONTINUA
    
        
