ORG 0100H

.MODEL SMALL

.DATA

.CODE

;MODO INMEDIATO
MOV AX,1003H          ;ASIGNO 1003H EN AX

;MODO INDIRECTO

MOV AX,0000H          ;LIMPIO AX

MOV BX,3410H          ;ASIGNO 3410H EN BX

MOV AH,BL             ;ASIGNO BL=10H EN AH

;MODO DIRECTO
                      ;ASIGNO 00FFH EN DX
MOV DX,00FFH
MOV DS:[0020H],DX     ;ASIGNO DX EN SEGMENTO DE DATO POSICION:[0020H]

MOV AX,DS:[0020H]     ;ASIGNO VALOR ALMACENADO EN DS:[0020H] EN AX

MOV BX,[0020H]        ;ASIGNO VALOR EN POSICION DS:[0020H] EN BX  

;REGISTRO INDIRECTO

MOV DX,1AADH          ;ASIGNO 1AADH EN DX
MOV DS:[0020H],DX     ;ASIGNO DX EN DATA SEGMENT:[0020H]

MOV BX,0020H          ;ASIGNO 0020H EN BX

MOV AX,[BX]           ;ASIGNO EL VALOR CONTENIDO EN EL SEGMENTO DE DATOS UBICADO DADO EL DESPLAZAMIENTO CONTENIDO EN BX

;REGISTRO RELATIVO A LA BASE

MOV DX,1FFCH          ;ASIGNO 1FFCH EN DX
MOV DS:[0050H],DX     ;ASIGNO DX EN EL SEGMENTO DE DATOS POSICION 0050H

MOV BX,0020H          ;ASIGNO 0020H EN BX

MOV AX,DS:[BX+0030H]  ;ASIGNO EL VALOR CONTENIDO EN EL DS UBICADO POR LA OPERACION BX(REGISTRO BASE) + CONTANTE EN AX

;RELATIVO A UN REGISTRO INDICE
MOV DX,4ADH           ;ASIGNO 4ADH EN DX
MOV DS:[0A30H],DX     ;ASIGNO DX EN DS:[0A30H]

MOV SI,0A00H          ;ASIGNO 0A00H EN SI

MOV AX,[SI + 0030H]   ;ASIGNO DATA SEGMENT:[SI(REGISTRO INDICE FUENTE) + CONTANTE] EN AX

;INDEXADO A LA BASE
MOV DX,2323H          ;ASIGNO 2323H EN DX
MOV DS:[0050H],DX     ;ASIGNO DX EN DS:[0050H]
                   
MOV BX,0028H          ;ASIGNO 0028H EN BX

MOV SI,0020H          ;ASIGNO 0020H EN SI         
                   
MOV AX,[BX+SI+0002H]  ;ASIGNO DATA SEGMENT[BX(BASE) + SI(INDICE) + CONTANTE] EN AX

.EXIT 
