;SALIDA

;EJEMPLO MOSTRAR MENSAJE "UNA CADENA DE CARACTERTERES"

ORG 0100H ;CS:IP

MOV AH,0H   ;PARA CONFIGURAR VIDEO

MOV AL,0H   ;40X25 16 COLORES

INT 10H     ;EJECUTO INTERRUPCION 

;OFFSET: DESPLAZAMIENTO DE LA DIRECCION DONDE ESTA EL MENSAJE

MOV DX, OFFSET msje ;CARGO LA CADENA EN EL REGISTRO DX

MOV AH,9H   ;CONFIGURA PARA DESPLEGAR CADENA

INT 21H     ;EJECUTO INTERRUPCION

RET

msje db "Mensaje con int 21$"