;MOVER UN VALOR A UN REGISTRO

org 100         ;DIRECCION DE INICIO  
           
mov AX,00FFH    ;MUEVO UN VALOR AL REGISTRO AX

mov BX,AX       ;MUEVO UN VALOR DEL REGISTRO AX HACIA EL REGISTRO BX

mov BX,1000H    ;ASIGNO 1000H A BX

mov [0000H],BX  ;MUEVO EL VALOR DE BX A MEMORIA                      

mov AX,[0000H]  ;MUEVO EL VALOR EN MEMORIA [0000h] HACIA AX

mov AX,1DDDH    ;ASIGNO AAAA A AX

mov BX,1CCCH    ;ASIGNO CCCCH A BX   


;INTERCAMBIAR VALOR SIN USO DE MEMORIA ADICIONAL

xor AX,BX   ;XOR ENTRE AX,BX

xor BX,AX   ;AHORA BX TIENE EL ANTIGUO VALOR DE AX

xor AX,BX   ;AHORA AX TIENE EL ANTIGUO VALOR DE BX