;OPERACIONES CON CADENA BITS

ORG 100H

.MODEL SMALL    
    
.DATA
    
    registro DW 1FDAH
    
    contador DB 0
    
    mnsje1   DB 'Valor encontrado$'
    
    mnsje2   DB 'Valor no encontrado$'
    
.CODE

    MOV AX,@DATA
    
    MOV DS,AX       ;ESTABLESCO EL SEGMENTO DE DATOS DS
    
    ;EJEMPLO CONTAR NUMERO ACTIVOS EN UN REGISTRO
    
    MOV CX,000FH      ;NUMERO DE BITS EN UN REGISTRO DE 16 BITS
    
    MOV AX,0001H ;CARGAR EL REGISTRO EN AX
    
    XOR BL,BL       ;INICIALIZAR EL CONTADOR EN 0
    
CONTAR_BITS:
    
    SHR AX,1        ;DESPLAZAR EL BIT MAS A LA DERECHA 
    
    JC INCREMENTAR_CONTADOR    ;SI EL BIT DESPLAZADO ES 1, INCREMENTAR EL CONTADOR
    
    LOOP CONTAR_BITS    ;REPETIR EL PROCESO HASTA QUE SE HAYAN EXAMINADO TODOS LOS BITS
    
JMP FIN_CONTAR_BITS

INCREMENTAR_CONTADOR:

    INC BL  ;INCREMENTAR EL CONTADOR
    
    LOOP CONTAR_BITS    ;REPETIR EL PROCESO HASTA QUE SE HAYAN EXAMINADO TODOS LOS BITS

FIN_CONTAR_BITS:

    MOV CONTADOR,BL     ;ALMACENAR EL RESULTADO EN LA VARIABLE 'CONTADOR'

    ;EJEMPLO ROTAR BITS
    
    MOV AX,0F0FH        ;ASIGNO 0F0FH EN AX
    
    MOV Cl,3            ;NUMERO DE BITS A ROTAR
    
    ROL AX,CL           ;ROTAR EL REGISTRO AX A LA IZQUIERDA POR CL BITS
    
    ;EL REGISTRO AX AHORA CONTENDRA EL VALOR ROTADO
    
    MOV AX,20F0H        ;ASIGNO F0F0H EN AX
    
    MOV CX,2            ;NUMERO DE BIT A ROTAR
    
    ROR AX,CL           ;NUMERO DE BITS A ROTAR A LA DERECHA POR CL BITS
    
    ;EJEMPLO ENCONTRAR EL BIT MAS SIGNIFICATIVO
    
    MOV AX,1FFFH        ;CARGO EL REGISTRO AX
    
    MOV CX,15H          ;INICIALIZAR EL CONTADOR EN 15(NUMERO DE BITS EN UN REGISTRO DESDE EL O AL 15)
    
ROTAR_A_LA_IZQUIERDA:
    
    RCL AX,1            ;ROTAR AL REGISTRO A LA IZQUIERDA, EL BIT DE ACARREO SERA EL MAS SIGNIFICATIVO
    
    JC ENCONTRE_EL_MAS_SIGNIFICATIVO
    
    DEC CX
    
    JZ  NO_ENCONTRADO
    
    JMP ROTAR_A_LA_IZQUIERDA
    
ENCONTRE_EL_MAS_SIGNIFICATIVO:
    
    MOV DX,OFFSET mnsje1
    
    MOV AH,9H
    
    INT 21H
    
    JMP FIN
    
NO_ENCONTRADO:

    MOV DX,OFFSET mnsje2
    
    MOV AH,9H
    
    INT 21H
        
    JMP FIN
    
FIN:

    ;CONTINUO...    
    
    