;OPERACIONES DE SISTEMA

ORG 100H

.MODEL SMALL

.DATA

    fechaYhora DB 20 DUP(?)   ;ESPACIO PARA ALMACENAR LA FECHA(FORMATO DD-MM-YYYY)
    
    variable_entorno DB "PATH=" ;VARIABLE DE ENTORNO QUE QUEREMOS OBTENER
    
    valor DB 128 DUP(?)         ;BUFFER PARA ALMACENAR EL VALOR DE LA VARIABLE DE ENTORNO
    
    ;ASUMO QUE ESTA EN EL MIMO DIRECTORIO SINO PONER LA RUTA COMPLETA
    
    nombre_programa DB 'EXEC.EXE', 0    ;NOMBRE DEL PROGRAMA HIJO A EJECUTAR

    ;COMANDO
    
    comando DB 'TASKILL /F /IM EXEC.EXE',0

.CODE

    MOV AX,@DATA
    
    MOV DS,AX           ;CARGO EL SEGMENTO DE DATOS
                            
    ;OBTENER LA FECHA DEL SISTEMA
              
    MOV AH,2AH          ;FUNCION 2AH DE LA INTERRUPCION 21H: OBTENER LA FECHA Y HORA
    
    INT 21H             ;LLAMAR A LA INTERRUPCION 21H
    
    MOV AH,0009H
    
    LEA DX,fechaYhora
    
    int 21h
    
    ;EJEMPLO ACCEDER A PARAMETRO DE LA LINEA
    
    MOV AH,09H          ;FUNCION DE LA INTERRUPCION 21H: MOSTRAR UNA CADENA DE CARACTERES
    
    ;EL PRIMER PARAMETRO DE LA LINEA DE COMANDO ESTA EN [BP+2]
    
    MOV DX,[BP+2]       ;CARGAR LA DIRECCION DEL PRIMER PARAMETRO EN DX
    
    INT 21H
    
    ;EL SEGUNDO PARAMETRO DE LA LINEA DE COMANDOS ESTA EN [BP+4]
    
    MOV DX,[BP+4]       ;CARGAR LA DIRECCION DEL SEGUNDO PARAMETRO EN DX
    
    INT 21H
    
    ;EL CODIGO SIGUE...
    
    ;EJEMPLO ACCEDER A VARIABLES DE ENTORNO
    
    MOV AH,62H      ;FUNCION 62H DE LA INTERRUPCION 21H: OBTENER EL PSP
    
    INT 21H
    
    MOV BX,2CH      ;OFFSER DE LA TABLA DEL SEGMENTO DEL PSP QUE CONTIENE LA DIRRECCION DE LAS VARIABLES DE ENTORNO
    
    MOV ES,AX       ;CARGAR EL SEGMENTO DEL PSP EN ES
    
    MOV DI,BX       ;CARGAR EL OFFSET DE LA TABLA DE SEGMENTO EN DI
    
    LEA DI,variable_entorno ;CARGAR LA DIRECCION DE LA VARIABLE DE ENTORNO EN SI
    
buscar_variable_entorno:

    LODSB              ;CARGAR EL SIGUIENTE BYTE DE SI EN AL Y AVANZAR SI
    
    CMP AL,'='         ;VERIFICAR SI EL BYTE ES '='
    
    JNE no_coincide    ;SI NO ES '='
    
    CALL comparar_nombre_variable_entorno   ;COMPARAR EL NOMBRE DE LA VARIABLE DE ENTORNO CON "PATH"
    
    JC encontrado      ;SI LA COMPARACION ES EXITOSA, SALTAR A ENCONTRADO
    
    jmp siguiente      ;SI NO SE ENCONTRO, AVANZAR A LA SIGUIENTE ENTRADA DE LA TABLA DE SEGMENTO DE ENTORNO
    
comparar_nombre_variable_entorno:

    MOV CX,0005H       ;LONGITUD DEL NOMBRE DE LA VARIABLE DE ENTORNO "PATH"
    
    REPZ CMPSB         ;COMPARAR LOS PRIMERO 5 BYTES DE SI CON "PATH"
    
    RET                ;DEVUELVE EL RESULTADO DE LA COMPARACION
    
siguiente:

    LODSB              ;SALTAR EL VALOR DE LA VARIABLE DE ENTORNO
    
    CMP AL,'$'         ;VERIFICAR SI LLEGAMOS AL FINAL DEL VALOR
    
    JNE buscar_variable_entorno ;SI NO ES "$", CONTINUAR BUSCANDO
    
    JMP no_encontrado   ;SI ES "$", LA VARIABL DE ENTORNO NO SE ENCONTRO
    
encontrado:
    
    INC SI              ;SALTAR EL '='
    
    MOV CX,128h         ;LONGITUD MAXIMA DEL VALOR DE LA VARIABL DE ENTORNO
    
    MOV DI,OFFSET valor ;CARGAR LA DIRECCION DEL BUFFER VALOR EN DI
    
    REP MOVSB           ;COPIAR EL VALOR DE LA VARIABLE DE ENTORNO EN EL BUFFER VALOR
    
    JMP fin             ;SALTAR AL FIN DEL PROGRAMA
    
no_coincide:

    CMP AL,'$'          ;VERIFICAR SI LLEGAMOS AL FINAL DE LA TABLA DE SEGMENTO DE ENTORNO
    
    JNE buscar_variable_entorno ;SI NO ES "$", CONTINUAR BUSCANDO
    
    JMP no_encontrado   ;SI ES "$", LA VARIABLE DE ENTORNO NO SE ENCONTRO
    
no_encontrado:

    MOV byte ptr[valor], '$'   ;ESTABLECER EL VALOR COMO CADENA VACIA
    
    JMP fin                     ;SALTAR EL FIN DEL PROGRAMA
    
fin:

    ;EJEMPLO EJECUTAR UN PROCESO
    
    ;LA VARIABLE DE ENTORNO ESTA AHORA EN EL BUFFER VALOR
    
    MOV AH,4BH  ;CARGAR Y/0 EJECUTAR UN PROGRAMA
    
    MOV DX,OFFSET nombre_programa  ;CARGAR EL NOMBRE DEL PROGRAMA A EJECUTAR EN DX
    
    INT 21H ;LLAMAR A LA INTERRUPCION 21H PARA EJECUTAR EL PROGRAMA HIJO
    
    ;TERMINAR UN PROCESO
    
    MOV DX,OFFSET comando   ;CARGAR EL COMANDO A EJECUTAR EN DX
    
    INT 21H
    
    ;EL CODIGO CONTINUA...    
    
        