;USO DE CONTADOR

ORG 100H

.MODEL SMALL

.STACK 100H

.DATA

.CODE

    MOV AL,10H      ;ASIGNO 10H EN AL
    
    MOV AH,00H      ;ASIGNO 00H EN AH
    
    MOV BX,0000H    ;BLANQUEO MI CONTADOR
    
    MOV CX,AX       ;CATIDAD DE VECES A REPETIR
    
    BLOQUE:         ;BLOQUE A REPETIR CX CATIDAD DE VECES
               
        CMP AH,AL   ;AH - AL RESTA LOGICA QUE ATIVA LAS VANDERAS
        
        JP ESPAR    ;BANDERA DE PARIDAD ACTIVA SALTO HACIA ESPAR
        
        CONTINUAR:  ;CONTINUO CONTANDO
        
        INC AH      ;INCREMENTO AH 
    
    LOOP BLOQUE     ;DECREMENTA CS SI MIENTRAS CX<>0 REPITE EL BLOQUE
    
    JMP FIN         ;SALTO CONDICIONAL PARA SALTARSE EL BLOQUE ES PAR
    
    ESPAR:              ;BLOQUE SI ES PAR
    
        INC BX          ;INCREMENTO MI CONTADOR
        
        JMP CONTINUAR   ;CONTINUO EL LOOP
    
    FIN:
    
.EXIT